### ISSUE TITLE
Performances ?

### ISSUE THREAD

**Issue by popod** [oliver-moran/jimp#170]
It seem that this lib take more time that all others.. have you performances optimisation in progress or bench ?

**Comment by oliver-moran** [comment]
This library takes longer because it is written entirely in JavaScript with no native dependencies. That's its unique selling point.

The advantage of being written entirely in JavaScript is portability, ease of installation, being able to contribute/debug in JS, etc.. But the drawback is that it's slower compared to using a native library - since everything is written in JavaScript.

It's up to you whether the performance of a native library is needed for your application. Or if the advantages of an entirely JS-based library trump performance needs.

Performances bench marking of various libraries are here: http://sharp.dimens.io/en/stable/performance/
