### ISSUE TITLE
unknown JPEG marker ffff

### ISSUE THREAD

**Issue by italoandrade** [oliver-moran/jimp#177]
I have an image that throw this error "unknown JPEG marker ffff", but the image is a normal JPEG. How can I fix this problem?

**Comment by oliver-moran** [comment]
Thanks for this. Can you upload a test image?

**Comment by italoandrade** [comment]
Yes, here it is (Please, don't mind the name or the text on the image)

![ai-cara-como-amo-a-zuera](https://cloud.githubusercontent.com/assets/19225266/19690150/741fd452-9aae-11e6-9d9e-2f1171b19a1c.jpeg)

**Comment by alt234** [comment]
Seeing this issue as well. Any updates per chance?

**Comment by dvv** [comment]
It's jpeg-js related -- https://github.com/eugeneware/jpeg-js/pull/32
May be to update the dep?

**Comment by tim-king** [comment]
This is now fixed in jpeg-js 0.3.3 so update your dependency

**Comment by rtwalz** [comment]
Still seeing this issue, is the dependency updated?

**Comment by peter-mouland** [comment]
@rtwalz to see if the dependency has been updated, you can have a look in the `package.json`.

I guess, if this is causing any issues for anyone else, a PR would probably be appreciated and confirmation the update doesn't break anything else.

**Comment by rtwalz** [comment]
@peter-mouland It was my fault, I was unintentionally removing the end from an image URL. Thanks for the quick response regardless!

**Comment by carterbancroft** [comment]
This is not fixed in jpeg-js 0.3.3. After seeing the comment above I attempted to put together a PR but the unit tests still fail with unknown JPEG marker error.

It's fixed in this commit to jpeg-js https://github.com/eugeneware/jpeg-js/commit/e5de15abe710b607de9cf251d83c5a9b04b46d5c but it's not released yet. I asked in the original PR if we could get a release on that and if a new version is minted I'll submit a PR with tests for this issue.
