### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by vclteam** [oliver-moran/jimp#18]
i tested jimp on hundreds of images. and im keep getting out of memory. 

any chances that there is a problem?

**Comment by oliver-moran** [comment]
Can you post the smallest possible test case and I'll take a look? Thanks.

**Comment by oliver-moran** [comment]
OK, I've done some testing. It's very easy to run out of memory doing something like this:

    for (var i = 0; i < 10000; i++) {
        var lenna = new Jimp("lenna.png", function (err, image) {
            // asynchronous callback
        });
    }

That's because you will really rapidly load 10,000 odd images into memory and try to work with them all at once. The correct thing to do is to load one image, work with it, and then (when you are done) load the next.

Is this what is happening for you?

**Comment by vclteam** [comment]
im still checking it. 
but at the moment im getting out of memory on 6 images running simultaneously. (all of them are less then 1 mb)

**Comment by oliver-moran** [comment]
I've tested opening, manipulating and saving > 160,000 images. Didn't come across a leak.

Any joy on a test case?

**Comment by vclteam** [comment]
looks ok
