### ISSUE TITLE
Using Stream to do asynchrone and parallele job

### ISSUE THREAD

**Issue by Yimiprod** [oliver-moran/jimp#24]
Is there a way to use stream?
I'm using jimp in a node-webkit app and each time i resize and crop a file the app freeze during the job. I wrapped everything in a promise but nothing seem to change, it's still synchrone and freeze my app.

**Comment by oliver-moran** [comment]
Node is single threaded environment. This means that while your application is doing one thing (e.g. resizing an image) it cannot do other things (e.g. responding to mouse clicks).

This is a "by design" characteristic of Node and has nothing to do with Jimp or any other module.

However, Node is an asynchronous environment. This means that it can call other processes (e.g. run an external script that resizes an image) and do other things while it waits for the response.

The easiest way to do this is to write a small command-line script that resizes images using Jimp (it could take an arguments, such as the desired size and a path to a file). Call this script as a child process from your main app and it won't block your application.

See documentation on child processed here: https://nodejs.org/api/child_process.html

**Comment by Yimiprod** [comment]
I was looking this direction but not sure about it.
Thanks for your reply.
