### ISSUE TITLE
NPM is out of date - needs a publish

### ISSUE THREAD

**Issue by Ratismal** [oliver-moran/jimp#250]
Salutations,

As the subject says, the latest build available on NPM is out of date. The [convolution matrix](https://github.com/oliver-moran/jimp#convolution-matrix) functionality that was added 4 months ago is not available when installing from npm, I'm not sure about any other discrepency. Please increment the version number and publish so I don't have to do a git install every time. Thanks!

**Comment by Ratismal** [comment]
This has also been mention in #237

**Comment by smolnikov** [comment]
+1

**Comment by solfolango** [comment]
I can still confirm that npm is not up to date, even if the version number seems to be correct.

**Comment by sidonaldson** [comment]
Is anyone available to fix this? I looks like there are a few tickets waiting on the NPM update (I believe this can't be a PR but apologies if I'm mistaken)

**Comment by lunarraid** [comment]
+1

**Comment by oliver-moran** [comment]
Apologies for the lack of publishes. Integrated most of the pull requests and made a publish to NPM just now.

Anybody willing to lend a hand working though the PRs is more than welcome: https://github.com/oliver-moran/jimp/issues/219

Two notable things about this release:

1. Exif handling is not backwards compatible. Previously JPEGs were automatically rotated according to exif data. Not the `image.exifRotate()` method will have to be manually called. I'm not bumping the major version number to mark this because we are still on version a major version 0.

2. The browser version is broken (again). This is a very brittle part of the library and seems to regularly break for reasons unknown. Anybody willing and able to help fix that would be very welcome.

Thank you everyone who contributed to this version!

**Comment by arackaf** [comment]
Curious why you got rid of the auto-exif rotate - I thought that was a nice feature to have.

I assume `image.exifRotate()` is safe to call on all jpegs -- ie it will do nothing if nothing is needed?

**Comment by oliver-moran** [comment]
The reason was to do with this: https://github.com/oliver-moran/jimp/pull/245

Rather than adding a option object to disable an opinionated feature, I decided to put control back in the hands of the developer.

`image.exifRotate()` is safe to call on all images. If no exif data is there it will just do nothing.

**Comment by arackaf** [comment]
Yeah - seems fair, especially when there's such a simple method which does this.  lwip doesn't even have the method so you have to manually parse the exifData, determine which rotations are needed, then manually apply them.  This is still a huge win over that :)
