### ISSUE TITLE
There is any way to set dpi in file?

### ISSUE THREAD

**Issue by Joker9090** [oliver-moran/jimp#255]
I am reading a file with 300 DPI and the output is in 72 DPI. I want to keep 300 DPI in the final file

**Comment by thewizarodofoz** [comment]
According to WIkipedia:
> In printing, DPI (dots per inch) refers to the output resolution of a printer or imagesetter, and PPI (pixels per inch) refers to the input resolution of a photograph or image

So I believe you are referring to PPI. And in that case, as far as I understand, jimp does not manipulate the PPI of an image. Meaning - the number of pixels in the source will be the number of pixels in the Jimp object.

Anyway - could you provide some example of the issue you're experiencing?

**Comment by aditya2272sharma** [comment]
Generally the bit-depth of an image can be preserved by forcibly shrinking it's size by CSS or `height`/`width` attributes, that's what we generally do for HDPI images.

@Joker9090 - a suggested workaround will be, if you're trying to modify dimensions, don't reduce to actual pixel sizes, but to the twice or thrice of the size. Simple rule of thumb - if your 300dpi image is of 100x100 size, then reduce the dimensions by using CSS/height/width instead of `resize()`

**Comment by patheticcockroach** [comment]
I too would need this (well, PPI as per the second comment). Apparently this would just need some pHYs chunks manipulation https://superuser.com/questions/646896/how-to-change-dpi-of-a-png-file-in-command-line-without-imagemagick#comment833528_647003 / http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.pHYs

But from what I understood reading the code, it seems that Jimp depends on its dependencies for that (for instance pngjs, which doesn't support PPI manipulation... and doesn't want to! :/) https://github.com/lukeapage/pngjs/issues/70

**Comment by Kikketer** [comment]
I'm looking for the same functionality.  I realize that at the surface a 100x100px image at 72ppi/dpi is about 416.6x416.6 pixels but when attempting to simply print the files produced you have to scale them in the print settings.  Otherwise the printer will use the 72dpi resolution and produce a massive image (at poor quality).

Has anyone had any luck using something like: https://github.com/shutterstock/changeDPI ?

**Comment by floriancargoet** [comment]
@Kikketer changeDPI works for me in Node but I need to put atob & btoa in the global scope first:
```js
const Jimp = require("jimp");
// changeDPI depends on these browser functions
global.atob = require("atob");
global.btoa = require("btoa");
const changeDPI = require("changedpi");

async function getRetinaImageB64(url) {
  const img = await Jimp.read(url);
  const b64 = await img.getBase64Async(Jimp.AUTO);
  // retina density
  const b64_144 = changeDPI.changeDpiDataUrl(b64, 144);
  return b64_144;
}
```
