### ISSUE TITLE
Jimp working locally, but not on DigitalOcean droplet

### ISSUE THREAD

**Issue by ThriceGood** [oliver-moran/jimp#297]
hello, 

I'm having an issue where Jimp is working fine locally to resize and save files, but when i use the same code on a DigitalOcean droplet it is failing, my application is being "killed". I can save files to the file system on the droplet using express-fileupload's .mv function. But for some reason Jimp is having troubles. 

Would you have any idea as to what is the problem here? I am not sure if it is a problem with Jimp or with the server.

my Jimp code:

https://github.com/ThriceGood/Spots/blob/master/routes/index.js#L87

my working express-fileupload code:

https://github.com/ThriceGood/Spots/blob/master/routes/index.js#L77

the server is running Ubuntu 16.04, Node 6.11.0 and Jimp 0.2.28

**Comment by An2An96** [comment]
Same problem. When you save the picture on vds, the process crashes without any errors.

**Comment by hipstersmoothie** [comment]
@ThriceGood @An2An96  will close within a month if not given an update or example repo

**Comment by hipstersmoothie** [comment]
How about you @lovetrivedi

**Comment by hipstersmoothie** [comment]
Closed due to inactivity.

**Comment by marcoshmendes** [comment]
I faced the same problem on DigitalOcean when i try to rotate large images, the application just is killed without any error log.

I realized that this problem is caused by a lack of memory. The default droplet on DigitalOcean has 1GB RAM. So i upgraded to 2GB RAM and no more kills on the applications, it rotates the image.

Maybe the rotate function need a performance refactoring. On 2GB RAM droplet, the image is processed, however still slowly.

Above you can see details about image. (Ps. Sorry for not providing the file by itself, it's a private project data)

![img-rotate](https://user-images.githubusercontent.com/17493368/85360807-9ac56580-b4f0-11ea-85a8-247b9333ff01.png)


![IMG](https://user-images.githubusercontent.com/17493368/85360766-78334c80-b4f0-11ea-906f-841fcb00d437.png)
