### ISSUE TITLE
Question About Performance / Usage

### ISSUE THREAD

**Issue by Bluejay47** [oliver-moran/jimp#35]
Any idea what the performance of this would be or what would be your intended usage scenarios? Is this intended for production use or maybe just as a proof of concept project?

Thanks,

**Comment by oliver-moran** [comment]
It's intended for production.

The use case is for when image libraries with native dependencies (such as `node-gd` or `imagemagick`) are either not possible or undesirable. Alternatively, you could say that those libraries are for when this one is undesirable. Because this library has no native dependencies, it is always possible.

With regards to actual performance and desirability, that's a question for your precise use case. A quick test on my MacBook Air:

* Open a file, resize it, save it: 90ms
* Open a file then cloned it, resized it and saved it 10,000 times: about 15 minutes (or 90ms × 10,000)

If that suits by your needs then that suits your needs.

**Comment by Bluejay47** [comment]
Thanks, I appreciate your taking the time to answer the question.

**Comment by oliver-moran** [comment]
FYI here's an interesting tweet about performance of Jimp:
https://twitter.com/lovell/status/648039050620850176

It appears to be compatible to [lwip](https://www.npmjs.com/package/lwip):
https://github.com/lovell/sharp/issues/275#issuecomment-143526723
