### ISSUE TITLE
Difference between distance and diff?

### ISSUE THREAD

**Issue by yeung108** [oliver-moran/jimp#423]
May I ask what is the difference of image comparison using hamming distance and PixelMatch? 
If I want to have a effect more on the object comparison in the two images (ignoring the background), which one should be better for this usage?

Thanks so much!

**Comment by hipstersmoothie** [comment]
`diff` will return an image with differing pixels. that both try to calculate how similar the images are

jimp works on a pixel bitmap. it has no object detection built in, and it is out of scope of this library. ignoring the background is not an option since we don't detect that. If you can write an implementation that isn't to heave feel free to make a PR!
