### ISSUE TITLE
Could not get image MIME for Buffer <null> when i take image form url:'https://graph.facebook.com/890843584382401/picture?type=large&width=200&height=200'

### ISSUE THREAD

**Issue by dhavalsojitra8866** [oliver-moran/jimp#636]
If i use facebook url then it shows below error.
<--------------- code---------------->
var url='https://graph.facebook.com/890843584382401/picture?type=large&width=200&height=200'
var url1 = url.replace('?height=90&width=90', '?type=large&width=200&height=200')
jimp.read(url1, function(err, image) {
console.log("image ------>", image)

<--------------- error ---------------->
image ------> undefined
jimp Error : { Error: Could not find MIME for Buffer 
at Jimp.parseBitmap (/home/game/teenpatti-dev/node_modules/@jimp/core/dist/utils/image-bitmap.js:108:15)
at Jimp.parseBitmap (/home/game/teenpatti-dev/node_modules/@jimp/core/dist/index.js:498:32)
at /home/game/teenpatti-dev/node_modules/@jimp/core/dist/index.js:440:15
at /home/game/teenpatti-dev/node_modules/@jimp/core/dist/index.js:168:14
at /home/game/teenpatti-dev/node_modules/@jimp/core/dist/request.js:56:9
at IncomingMessage. (/home/game/teenpatti-dev/node_modules/phin/lib/phin.compiled.js:1:2162)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:139:11) methodName: 'constructor' }

**Comment by dhavalsojitra8866** [comment]
hipstersmoothie  what is the possible solution?

**Comment by hipstersmoothie** [comment]
I think I figured it out.

The url you are requesting is not in fact an image. If you open the url in your browser the image automatically downloads. Thats a hint it's not just an image. If you add `&redirect=false`. You can see what the actual response for the URL is.

https://graph.facebook.com/890843584382401/picture?type=large&width=200&height=200&redirect=false

```json
{
   "data": {
      "height": 200,
      "is_silhouette": false,
      "url": "https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=890843584382401&height=200&width=200&ext=1541921135&hash=AeSEa149-GbTzypV",
      "width": 200
   }
}
```

If you then use `https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=890843584382401&height=200&width=200&ext=1541921135&hash=AeSEa149-GbTzypV` as the url it will correctly download the image, since you are now actually requesting the image.

Does this solve your issue?

**Comment by dhavalsojitra8866** [comment]
No its did not solved my issue.
Because it only happen when i use "https://graph.facebook.com/" url.

**Comment by hipstersmoothie** [comment]
Yeah, graph urls for picture do some weird redirect thing so you have to get the url yourself. Why is the answer not sufficient?

**Comment by NexusLee** [comment]
Then I have to get the actual image url address by myself?

**Comment by hipstersmoothie** [comment]
Yes. 

fetch graph-url -> fetch image in response

**Comment by NexusLee** [comment]
@hipstersmoothie thank you

**Comment by spiceyavocado** [comment]
pppopo
