### ISSUE TITLE
Web build (jimp.min.js) missing

### ISSUE THREAD

**Issue by JannisX11** [oliver-moran/jimp#646]
# Expected Behavior

In v0.2.28 i used the "browser/lib/jimp.min.js" file to use Jimp both in a browser and in Electron.

# Current Behavior

The file jimp.min.js is missing from the current build and I can't find an alternative file in the repo.

**Comment by hipstersmoothie** [comment]
@JannisX11 I just installed v0.5.4 and the following code did not fail. I cannot reproduce your issue. 

```js
const Jimp = require('jimp/browser/lib/jimp.min.js');

test();

async function test() {
  const image = await Jimp.read('../exampleImages/anime.png');

  const b = await image.pixelate(4).getBufferAsync(Jimp.AUTO);
  console.log(b);
}
```

**Comment by JannisX11** [comment]
> @JannisX11 I just installed v0.5.4 and the following code did not fail. I cannot reproduce your issue.
> 
> ```js
> const Jimp = require('jimp/browser/lib/jimp.min.js');
> 
> test();
> 
> async function test() {
>   const image = await Jimp.read('../exampleImages/anime.png');
> 
>   const b = await image.pixelate(4).getBufferAsync(Jimp.AUTO);
>   console.log(b);
> }
> ```
> 
> can you provide me with a sample repo showcasing the problem?

I am not using Require in my web build. In the previous version I was simply loading the jimp.min.js script from the HTML document. In this version when I download the repo, this file is missing.

**Comment by hipstersmoothie** [comment]
If I can require the file it exists. Mind sharing code showcasing the
problem? I can’t reproduce so unless you give me a reproducible case I
won’t be able to fix this. I will be closing if you do not provide code
since it definitely works on my end.

It seems like that may just be an html file so it should be easy.

I think I just figured out your actual problem. You are downloading the
repo and not using npm to install. The built files are not hosted in the
repo. It is very uncommon for packages to work like that. You either must
install the nvm dependency, which is how the built files are distributed.
Or you can run the build yourself on the repo and the minified build will
be in packages/jimp/browser/lib/jimp.min.js. I will not be adding the built
files back to the github repo. So these are your only options

**Comment by JannisX11** [comment]
> I think I just figured out your actual problem. You are downloading the repo and not using npm to install. The built files are not hosted in the repo. It is very uncommon for packages to work like that. You either must install the npm dependency, which is how the built files are distributed. Or you can run the build yourself on the repo and the minified build will be in packages/jimp/browser/lib/jimp.min.js.

Thanks, this worked.

> Also this is why I have the steps to reproduce section in the issue template you deleted. That way i don't have to guess your problems and can just fix them

I think sections I filled were pretty self explainatory. There was no code involved, so I couldn't have made an example. It was just the file that was missing and I wasn't expecting it to be not in this repo anymore.
