### ISSUE TITLE
One image (at least) produces a hash(64) value of "0" ...

### ISSUE THREAD

**Issue by marcolino** [oliver-moran/jimp#66]
First bug... :-)

    var Jimp = require('jimp');

    var imageName = 'ts.jpg';

    Jimp.read(imageName, function(err, image) {
      if (err) {
        return console.error('Jimp can\'t read image:', err);
      }
      var hash64 = image.hash(64);
      if (hash64.length !== 11) {
        return console.error('hash value ('+hash64+') length is', hash64.length, 'instead of 11!');
      }
      console.log('hash64:', hash64);
    });

file "ts.jpg" is: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Taylor_Swift_112_%2818119055110%29.jpg/250px-Taylor_Swift_112_%2818119055110%29.jpg

All other images I am testing all return a hash lenght of 11 (why 11? :-)

**Comment by oliver-moran** [comment]
Caught the issue with Taylor. See latest in git. Will publish this evening after testing.

With regards to why the hash is 11 digits long, I suspect the reason is chance. Example: Pick random a number between 0 and 9999999. Nine out of ten times, it will be 7 digits long. One way of thinking about this is because the chance of the leading digit being zero is just 1 in 10 decimal. In base 64, the chance of the leading digit being zero is 1 in 64.

**Comment by oliver-moran** [comment]
This fix is published to NPM now. Thanks for catching it.
