### ISSUE TITLE
Crop is cropping the wrong way

### ISSUE THREAD

**Issue by mjabraham47** [oliver-moran/jimp#663]
I expect crop to follow the crop behavior I set forth on my front-end using react-image-crop.

Currently, when I send an image back for cropping, the image for some reason is cropped even smaller.  For example:
With crop object: {x: 67, y: 0, width: 133, height: 266}, I pass an image into Jimp.  Unfortunately, the below code has been providing even smaller cropped objects.  I checked, and I'm definitely passing the full image into Jimp. 
```

    return Jimp.read(decodedImage.data)
      .catch(function(err) {
        console.error(err);
      })
      .then(function(image) {
          console.log(imageObject.crop)
        return image.crop(
          imageObject.crop.x,
          imageObject.crop.y,
          imageObject.crop.width,
          imageObject.crop.height
        );
      })
```
I'm not sure if this is a bug or if perhaps I'm passing the parameters in incorrectly. 

- Jimp Version: Current 
- Operating System: OSX 10.13.6
- Node version: 7.8.0

**Comment by AmauriAires** [comment]
Hi @mjabraham47. Your code seems to work properly. I used it and it worked as expected. What are the dimensions of your image? @mjabraham47 and @hipstersmoothie, is there a more specific way to reproduce the problem mentioned above?

**Comment by hipstersmoothie** [comment]
I have not investigated this at all so far @AmauriAires. @mjabraham47 can you explain further? `imageObject` and `image` seem to be different things in you code

**Comment by nitinaggarwal1986** [comment]
The first image when read and written results into the second one. I think the writer is reading a few properties of reader wrong. 

![IMG_20190916_171604](https://user-images.githubusercontent.com/11847517/65025950-3a980680-d955-11e9-9748-b01fd6ce4fc0.jpg)
![boxB](https://user-images.githubusercontent.com/11847517/65025972-408de780-d955-11e9-946a-dab51db5ab93.jpg)

**Comment by Jroze88** [comment]
If your decodedImage.data object is binary data of the image you're feeding Jimp to read() then it's possible the rotation is due to the fact that exif information (including portrait vs landscape orientation) is lost when an image is written to a binary stream.

The black area results from handing the crop() function dimensions that don't match the image's resulting size after cropping to the x, y coordinates. It expands the canvas to the dimensions you gave it and then fills in the extra space with black.

Hope this helps!
