### ISSUE TITLE
Add "bevel" feature

### ISSUE THREAD

**Issue by JacobDB** [oliver-moran/jimp#680]
I'd love to be able to add a bevel to images, similar to the edge bevel in [Android Asset Studio](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=android&foreground.space.trim=1&foreground.space.pad=0.25&foreColor=rgb(255%2C%20255%2C%20255)&backColor=rgb(68%2C%20138%2C%20255)&crop=0&backgroundShape=circle&effects=none&name=ic_launcher). I don't see anything in the documentation on how to achieve this (`convulte` seems similar, but not quite what I need). IF this feature doesn't already exist, I'd greatly appreciate it being added in a future release.

**Comment by hipstersmoothie** [comment]
I'm looking at the tool and there are no options that mention bevel or edge. Do you mean you want to create a tiny border around the image?

I don't really see this feature coming to jimp, but you can probably achieve the effect by using a few functions. What exactly do you want? If you can carefully explain how it should look i will give it a shot

**Comment by JacobDB** [comment]
Ah, sorry, I should've been a bit more clear :)

Yes, I do mean adding a slight border effect, if you look at the icon in the screenshot below, you can see what I'm referring to around the edges.

![image](https://user-images.githubusercontent.com/1123997/50241584-746bba80-038d-11e9-8dae-bac27ea899b2.png)

**Comment by hipstersmoothie** [comment]
this border might be hard to achieve since it also has a slight gradient. I don't have time today to try to do this but here are the things I would try first:

- calculate the dark border color
- somehow mask it into the desired shape
- adjust the position of the dark area so the border is achieved
- repeat all this for the light color
- blit or composite all images into 1 image and layer accordingly.

**Comment by JacobDB** [comment]
Thanks, I'll try and take a look at how to do that when I have a few spare moments 🙂
