### ISSUE TITLE
Photo color quality is getting bad

### ISSUE THREAD

**Issue by canvas-manik** [oliver-moran/jimp#84]
Hi Oliver,

I am using Jimp v 0.2.15
I am trying to resize the image with the following piece of code:
Jimp.read(srcImgLocation, function (err, image) {
image.resize(width,height).quality(80).write(location,function(err,image){
}
}
I see the color quality of the image is getting bad.
P.S. attached the original and Jimped version of photo
![original](https://cloud.githubusercontent.com/assets/11735090/11904389/d2efd180-a5e5-11e5-87cd-2f552a6d277d.jpg)
Original
![jimped](https://cloud.githubusercontent.com/assets/11735090/11904388/d2e98af0-a5e5-11e5-94b1-1b0c11cc8034.jpg)
Jimped

**Comment by skoa-h** [comment]
Hi,

I think this is a problem with the color profile. Your jpg is Adobe RGB, jimp or the underlying jpg-js is quietly discarding the color profile which results in the second image.

**Comment by manikmi** [comment]
Hi Oliver,

Do we have a solution / workaround for this issue?
Truly appreciate your effort.

Regards,
Manik Mittal

**Comment by canvas-manik** [comment]
Hi Skoah,

Is there a way while loading the image, we can make out whether the image's color profile might be disregarded, so that I can bypass the Jimp process? Just as a work around for now.

**Comment by skoa-h** [comment]
Hi Manik,

the decoder of jpg-js is discarding every jpg header information except app0 (version, density, thumb data) and app14 (transformCode). There is also no color correction or conversion.

Internally jimp uses plain bitmap data after decoding the source image with jpg-js, it does not know anything about the loaded image nor its headers. So jimp would need functions to decode header information (color profiles, exif, iptc, xmp, ... quite alot) itself respectively to convert header information from one format to another.

I'm sorry but I think there is currently no short term workaround for this problem.

Regards,
Skoah

**Comment by oliver-moran** [comment]
It looks like colour profile to me too. The appropriate place to take that up would be the jpeg-js library: https://github.com/eugeneware/jpeg-js

That's what Jimp uses to read/write JPEGs, after which Jimp just pushes pixels around.

**Comment by skoa-h** [comment]
Hi Oliver,

the jpeg-js decoder decodes to plain rgba bitmap data and jimp needs that from all decoders I think.
So imho the safest way would be a solution in jimp to copy and maybe convert header information itself, like the exifrotate function also reads header information too.

Regards

**Comment by canvas-manik** [comment]
Hi Oliver / Skoah,

This image is not "CMYK". It is "RGB". I checked on http://regex.info/exif.cgi

**Comment by skoa-h** [comment]
Hi Manik

No it is not CMYK, it is RGB but it uses the color profile AdobeRGB. If you open it with an image viewer like xnview which ignores color correction profiles you will see no visual difference between both images. Browsers like Firefox, Internet Explorer or the Windows image preview apply the color correction, so there is a visual difference between both images.

Regards
Skoah

**Comment by canvas-manik** [comment]
Hi Oliver / Skoah,

I saw another issue, related to image quality. See the images below:

**Original Image:**
![unsplash_europe_photo-1429734160945-4f85244d6a5a](https://cloud.githubusercontent.com/assets/11735090/13071758/7e811384-d4bb-11e5-8c41-b05d3f03c851.jpg)

**Jimped image:**
![manik-00633683-ba9e-4d82-a41f-fb3437d0c770](https://cloud.githubusercontent.com/assets/11735090/13071805/c39f8e6e-d4bb-11e5-8e45-d74f21b65385.jpg)

Please check the haziness. of the walls, the water...
Truly appreciate the help.

**Comment by skoa-h** [comment]
Ahhh Hamburg, great city. :)

But the scaled image doesn't look good. It looks like the resize uses Nearest Neighbour interpolation, which results in this moiré effect.

In the code, I didn't find a clue to use another interpolation mode so I guess there is the need for a resize replacement. I can look into that, but I cannot make promises.

**Comment by skoa-h** [comment]
So I tested a replacement for the resize method and got the following results. The image is very problematic for resizing because of the structures resulting moiré.

**Resized using imagejs resize replacement in jimp:**
Bezier:
![hamburg-bezier-out](https://cloud.githubusercontent.com/assets/4972131/13080945/2e3d85c8-d4cb-11e5-9c9d-a4af3d19d253.jpg)
Bicubic
![hamburg-bicubic-out](https://cloud.githubusercontent.com/assets/4972131/13080951/33391d12-d4cb-11e5-8532-3ff42c537aeb.jpg)
Bilinear
![hamburg-bilinear-out](https://cloud.githubusercontent.com/assets/4972131/13080955/36f2d22c-d4cb-11e5-8ed8-590240f83b11.jpg)
Hermite
![hamburg-hermite-out](https://cloud.githubusercontent.com/assets/4972131/13080957/3972f1d0-d4cb-11e5-861f-84e951292231.jpg)
Nearest Neighbour
![hamburg-nearest_neighbour-out](https://cloud.githubusercontent.com/assets/4972131/13080960/3c4ed1da-d4cb-11e5-9e64-95ae19691391.jpg)

**Photoshop resize samples:**
Bicubic
![hamburg-bicubic-out-ps](https://cloud.githubusercontent.com/assets/4972131/13080966/42ec4608-d4cb-11e5-933f-f7719c63ccdf.jpg)
Bilinear
![hamburg-bilinear-out-ps](https://cloud.githubusercontent.com/assets/4972131/13080968/45239c96-d4cb-11e5-87f8-166b99f66dae.jpg)
Automatic
![hamburg-photoshop-out](https://cloud.githubusercontent.com/assets/4972131/13080971/484299e0-d4cb-11e5-8046-5ea76b290da3.jpg)

**Comment by skoa-h** [comment]
Just to double check I resized the image with jimp myself and I got the following result:
![hamburg-legacy-out](https://cloud.githubusercontent.com/assets/4972131/13110886/e0fe2f0c-d582-11e5-8286-919924ca6caf.jpg)

It's not nearly as distorted as your result.

**Comment by oliver-moran** [comment]
Thanks. Updated resize methods will be in the next release.

**Comment by oliver-moran** [comment]
Closing and keeping one colour profile issue here: https://github.com/oliver-moran/jimp/issues/88
